version: "3.3"

services:
  qbittorrent:
    image: "linuxserver/qbittorrent"
    volumes:
      - "qbittorrent.config:/config"
      - "storage.downloads:/downloads"
    ports:
      - "6881:6881"
      - "6881:6881/udp"
    deploy:
      labels:
        traefik.backend: "qbittorrent"
        traefik.frontend.rule: "Host:torrent.docker"
        traefik.docker.network: "dev_reverse-proxy"
        traefik.port: 8095
    environment:
      PUID: "33"
      PGID: "33"
      TZ: "Europe/Paris"
      UMASK_SET: "022"
      WEBUI_PORT: "8095"
    networks:
      dev_reverse-proxy: ~

  jackett:
    image: "linuxserver/jackett"
    volumes:
      - "jackett.config:/config"
    deploy:
      labels:
        traefik.backend: "jackett"
        traefik.http.frontend.rule: "Host:jackett.docker"
        traefik.docker.network: "dev_reverse-proxy"
        traefik.port: 9117
    networks:
      dev_reverse-proxy: ~

  radarr:
    image: "linuxserver/radarr"
    volumes:
      - "radarr.config:/config"
      - "storage.downloads:/downloads"
      - "storage.movies:/movies"
    deploy:
      labels:
        traefik.backend: "radarr"
        traefik.http.frontend.rule: "Host:radarr.docker"
        traefik.docker.network: "dev_reverse-proxy"
        traefik.port: 7878
    environment:
      PUID: "0"
      PGID: "0"
    networks:
      dev_reverse-proxy: ~

  emby:
    image: "emby/embyserver"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "emby.config:/config"
      - "storage.movies:/media/movies:ro"
    deploy:
      labels:
        traefik.backend: "emby"
        traefik.frontend.rule: "Host:emby.docker"
        traefik.docker.network: "dev_reverse-proxy"
        traefik.port: 8096
    networks:
      dev_reverse-proxy: ~

volumes:
  emby.config: ~
  jackett.config: ~
  qbittorrent.config: ~
  radarr.config: ~
  storage.downloads: ~
  storage.movies: ~

networks:
  dev_reverse-proxy:
    external: true
