version: '3.3'

services:
  portainer:
    image: "portainer/portainer"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "data:/data"
    deploy:
      labels:
        traefik.frontend.rule: "Host:portainer.docker"
        traefik.docker.network: "dev_reverse-proxy"
        traefik.port: 9000
    networks:
      dev_reverse-proxy: ~

volumes:
  data: ~

networks:
  dev_reverse-proxy:
    external: true
